defaults:
  - weights/weights_base
lr: 1e-4
n_iter: 10
n_ims: 1
grad_clip: -1
# choices: ["adversarial", "corruption"]
shift_method: "adversarial"
loss_name: 'iou'
method: "tent"
train_norm_only: 0
gt_learnt: 1
severities: "1,3,5"